// Generated by tools/generate-transport-config.mjs. Do not edit.
export const TRANSPORT = Object.freeze({
  "host": "127.0.0.1",
  "port": 32189,
  "path": "/v1/client",
  "subprotocol": "browser-key-client-v1",
  "product": "browser-key-automation",
  "profile": "browser-key-loopback-v1",
  "protocolVersion": 1,
  "maximumMessageBytes": 65536,
  "maximumHttpHeadBytes": 8192,
  "maximumOnlineExtensions": 64,
  "handshakeTimeoutMs": 10000,
  "defaultReadTimeoutMs": 130000,
  "maximumReadTimeoutMs": 900000
});
