import { TRANSPORT_CONFIG } from "./generated/transport-config.js";

type TransportState =
  | { readonly kind: "transport.connecting" }
  | {
      readonly kind: "transport.connected";
      readonly connectionGeneration: number;
      readonly capabilities: readonly string[];
    }
  | { readonly kind: "transport.disconnected"; readonly retryInMs: number }
  | { readonly kind: "transport.protocol-error"; readonly detail: string }
  | {
      readonly kind: "transport.inbound";
      readonly connectionGeneration: number;
      readonly capabilities: readonly string[];
      readonly payload: unknown;
    };

const encoder = new TextEncoder();
const decoder = new TextDecoder("utf-8", { fatal: true });

let activeSocket: WebSocket | undefined;
let reconnectTimer: number | undefined;
let handshakeTimer: number | undefined;
let stopped = false;
let generation = 0;
let applicationReady = false;
let applicationCapabilities: readonly string[] = [];

function publish(state: TransportState): void {
  postMessage(state);
}

function scheduleReconnect(): void {
  if (stopped || reconnectTimer !== undefined) return;
  publish({
    kind: "transport.disconnected",
    retryInMs: TRANSPORT_CONFIG.retryIntervalMs,
  });
  reconnectTimer = setTimeout(() => {
    reconnectTimer = undefined;
    connect();
  }, TRANSPORT_CONFIG.retryIntervalMs);
}

function disconnect(socket: WebSocket, reason = "transport disconnected"): void {
  if (activeSocket !== socket) return;
  activeSocket = undefined;
  applicationReady = false;
  applicationCapabilities = [];
  if (handshakeTimer !== undefined) {
    clearTimeout(handshakeTimer);
    handshakeTimer = undefined;
  }
  socket.close(1000, reason);
  scheduleReconnect();
}

function closeForProtocolError(socket: WebSocket, detail: string): void {
  publish({ kind: "transport.protocol-error", detail });
  disconnect(socket, "protocol error");
}

function decodeBinaryMessage(data: unknown): unknown {
  if (!(data instanceof ArrayBuffer)) {
    throw new Error("relay sent a non-binary message");
  }
  if (data.byteLength > TRANSPORT_CONFIG.maximumMessageBytes) {
    throw new Error("relay message exceeded the generated byte limit");
  }
  return JSON.parse(decoder.decode(data)) as unknown;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isRelayHello(value: unknown): boolean {
  return (
    isRecord(value) &&
    value.kind === "relay.hello" &&
    value.product === TRANSPORT_CONFIG.product &&
    value.transportProfile === TRANSPORT_CONFIG.profileId &&
    value.protocolVersion === TRANSPORT_CONFIG.protocolVersion &&
    typeof value.relayEpoch === "string"
  );
}

function extensionCapabilities(value: unknown): readonly string[] | null {
  if (!isRecord(value) || value.kind !== "role.ready" || value.role !== "extension") return null;
  if (value.capabilities === undefined) return [];
  if (!Array.isArray(value.capabilities) || !value.capabilities.every((entry) => typeof entry === "string")) return null;
  const capabilities = [...value.capabilities];
  return new Set(capabilities).size === capabilities.length ? capabilities : null;
}

function sendRoleHello(socket: WebSocket): void {
  socket.send(
    encoder.encode(
      JSON.stringify({
        kind: "role.hello",
        role: "extension",
        protocolVersion: TRANSPORT_CONFIG.protocolVersion,
      }),
    ),
  );
}

function connect(): void {
  if (stopped || activeSocket !== undefined) return;
  generation += 1;
  applicationReady = false;
  applicationCapabilities = [];
  const connectionGeneration = generation;
  publish({ kind: "transport.connecting" });

  let socket: WebSocket;
  try {
    socket = new WebSocket(
      TRANSPORT_CONFIG.webSocketUrl,
      TRANSPORT_CONFIG.extensionSubprotocol,
    );
  } catch {
    scheduleReconnect();
    return;
  }

  activeSocket = socket;
  socket.binaryType = "arraybuffer";
  let handshakePhase: "relay-hello" | "role-ready" | "ready" = "relay-hello";
  handshakeTimer = setTimeout(() => {
    if (activeSocket === socket && connectionGeneration === generation && !applicationReady) {
      disconnect(socket, "handshake timeout");
    }
  }, TRANSPORT_CONFIG.handshakeTimeoutMs);

  socket.addEventListener("open", () => {
    if (activeSocket !== socket || connectionGeneration !== generation) return;
    if (socket.protocol !== TRANSPORT_CONFIG.extensionSubprotocol) {
      closeForProtocolError(socket, "relay selected the wrong WebSocket subprotocol");
    }
  });

  socket.addEventListener("message", (event) => {
    if (activeSocket !== socket || connectionGeneration !== generation) return;
    let message: unknown;
    try {
      message = decodeBinaryMessage(event.data);
    } catch (error) {
      closeForProtocolError(
        socket,
        error instanceof Error ? error.message : "invalid relay message",
      );
      return;
    }

    if (handshakePhase === "relay-hello") {
      if (!isRelayHello(message)) {
        closeForProtocolError(socket, "invalid relay hello");
        return;
      }
      handshakePhase = "role-ready";
      sendRoleHello(socket);
      return;
    }

    if (handshakePhase === "role-ready") {
      const capabilities = extensionCapabilities(message);
      if (capabilities === null) {
        closeForProtocolError(socket, "invalid extension role acknowledgement");
        return;
      }
      handshakePhase = "ready";
      if (handshakeTimer !== undefined) {
        clearTimeout(handshakeTimer);
        handshakeTimer = undefined;
      }
      applicationReady = true;
      applicationCapabilities = capabilities;
      publish({ kind: "transport.connected", connectionGeneration, capabilities });
      return;
    }

    publish({
      kind: "transport.inbound",
      connectionGeneration,
      capabilities: applicationCapabilities,
      payload: message,
    });
  });

  socket.addEventListener("error", () => {
    disconnect(socket);
  });

  socket.addEventListener("close", () => {
    if (activeSocket !== socket || connectionGeneration !== generation) return;
    disconnect(socket);
  });
}

addEventListener("message", (event: MessageEvent<unknown>) => {
  if (!isRecord(event.data)) return;
  if (event.data.kind === "transport.outbound") {
    if (
      event.data.connectionGeneration !== generation ||
      !applicationReady ||
      activeSocket?.readyState !== WebSocket.OPEN
    ) {
      return;
    }
    activeSocket.send(encoder.encode(JSON.stringify(event.data.payload)));
    return;
  }
  if (event.data.kind !== "transport.stop") return;
  stopped = true;
  if (reconnectTimer !== undefined) {
    clearTimeout(reconnectTimer);
    reconnectTimer = undefined;
  }
  const socket = activeSocket;
  if (socket !== undefined) disconnect(socket, "transport stopped");
});

connect();
